[tool.poetry]
name = "dsmusic"
version = "0.2.1"
description = "A simple music bot"
license = "MIT"
authors = ["John Toniutti <john.toniutti@gmail.com>"]
readme = "README.md"
classifiers = [
    "Development Status :: 4 - Beta",
    "Environment :: Console",
    "Framework :: aiohttp",
    "License :: OSI Approved :: MIT License",
    "Natural Language :: English",
    "Programming Language :: Python :: 3.11",
    "Topic :: Communications :: Chat",
]

[tool.poetry.dependencies]
python = "^3.11"
discord-py = "^2.3.2"
uvloop = { version = "^0.17", markers = "sys_platform == 'linux'" }
orjson = "^3.8.0"
aiodns = "^3.0.0"
brotli = "^1.1.0"
mafic = "^2.9.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
